language: cpp
sudo: required

matrix:
  include:
    # Linux build
    - os: linux
      env: TOOLCHAIN=local.cmake
    # Windows build
    - os: linux
      env: TOOLCHAIN=linux_to_windows.cmake
      addons:
        apt:
          packages:
            - g++-mingw-w64-base
            - gcc-mingw-w64-base
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
            - g++-mingw-w64-x86-64
            - gcc-mingw-w64
            - g++-mingw-w64

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

script:
  - mkdir build
  - cd build
  - echo "$TOOLCHAIN"
  - cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_TOOLCHAIN_FILE="../external/cmake_toolchain_templates/$TOOLCHAIN" ..
  - make

