language: cpp

matrix:
  include:
    # Linux build
    - os: linux
      env: TOOLCHAIN=local.cmake
    # Windows build
    - os: linux
      env: TOOLCHAIN=linux_to_windows.cmake
      addons:
        apt:
          packages:
            - g++-mingw-w64-base
            - gcc-mingw-w64-base
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
            - g++-mingw-w64-x86-64
            - gcc-mingw-w64
            - g++-mingw-w64

before_script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_TOOLCHAIN_FILE=../external/cmake_toolchain_templates/"$TOOLCHAIN" ..

script: make

